; generated by PrusaSlicer 2.7.4+win64 on 2026-08-01 at 09:14:22 UTC
; total layers count = 3
M568 P0 R140 S200
M568 P1 R140 S205
G28 ; home all
G90
M83
T0
;LAYER_CHANGE
;Z:0.2
G1 Z0.2 F720
G1 X10 Y10 F6000
G1 X100 Y10 E5 F1800
G1 X100 Y100 E5 F1800
G1 X10 Y100 E5 F1800
T1
G1 X10 Y10 F6000
G1 X100 Y10 E5 F1800
;LAYER_CHANGE
;Z:0.4
G1 Z0.4 F720
G1 X10 Y10 F6000
G1 X100 Y10 E5 F1800
G1 X100 Y100 E5 F1800
T0
G1 X10 Y100 E5 F1800
G1 X10 Y10 E5 F1800
;LAYER_CHANGE
;Z:0.6
G1 Z0.6 F720
G1 X10 Y10 F6000
G1 X100 Y10 E5 F1800
M568 P0 A0
M568 P1 A0
M107
; filament used [mm] = 84.0
; --- Eject sequence template: every line below is commented out ---
; Uncomment and check the coordinates for YOUR machine before using this.
; M400 ; wait for pending moves to finish
; G91 ; relative positioning
; G1 Z10 F600 ; lift the nozzle clear of the part
; G90 ; back to absolute positioning
; G1 X0 Y300 F6000 ; move the bed or gantry to the eject position
; M84 ; disable motors
