; generated by OrcaSlicer 2.1.0 on 2026-02-14 at 18:02:11
; total layer number: 3
; total filament used [g] = 0.04
M73 P0 R1
M201 X20000 Y20000 Z500 E5000
M104 S220
M140 S60
G28
M486 A"cube" S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z0.2 F600
;TYPE:Outer wall
G1 X90 Y90 E0.5 F3000
G1 X110 Y90 E0.5
;LAYER_CHANGE
;Z:0.4
G1 Z0.4 F600
;TYPE:Outer wall
G1 X110 Y110 E0.5 F3000
M486 S-1
;LAYER_CHANGE
;Z:0.6
G1 Z0.6 F600
G1 X90 Y110 E0.5 F3000
M104 S0
M140 S0
; --- Eject sequence template: every line below is commented out ---
; Uncomment and check the coordinates for YOUR machine before using this.
; M400 ; wait for pending moves to finish
; G91 ; relative positioning
; G1 Z10 F600 ; lift the nozzle clear of the part
; G90 ; back to absolute positioning
; G1 X0 Y300 F6000 ; move the bed or gantry to the eject position
; M84 ; disable motors
