import { describe, expect, it } from "vitest";

import { analyseText } from "../model/analysis";
import { compareAnalyses } from "../model/compareFiles";
import { parseMetadata } from "../model/gcode/metadata";

function analyse(text: string) {
	return analyseText(text, parseMetadata(text));
}

const SMALL = [
	"; generated by PrusaSlicer 2.7.4 on 2026-01-01",
	"; filament used [mm] = 1000.0",
	"; estimated printing time (normal mode) = 10m",
	"M104 S200",
	"M140 S60",
	"G28",
	"G90",
	"M83",
	"T0",
	";LAYER_CHANGE",
	"G1 X10 Y10 E1 F1800",
].join("\n");

const BIGGER = [
	"; generated by PrusaSlicer 2.7.4 on 2026-01-01",
	"; filament used [mm] = 2000.0",
	"; estimated printing time (normal mode) = 20m",
	"M104 S220",
	"M140 S65",
	"G28",
	"G90",
	"M83",
	"T0",
	";LAYER_CHANGE",
	"G1 X10 Y10 E1 F1800",
	";LAYER_CHANGE",
	"G1 X20 Y20 E1 F1800",
].join("\n");

describe("compareAnalyses", () => {
	it("returns the same value on both sides for two identical files", () => {
		const a = analyse(SMALL);
		const rows = compareAnalyses(a, a);
		expect(rows.length).toBeGreaterThan(0);
		for (const r of rows) {
			expect(r.a).toBe(r.b);
			expect(r.same).toBe(true);
		}
	});

	it("flags rows that actually differ, and leaves unrelated rows marked as the same", () => {
		const a = analyse(SMALL);
		const b = analyse(BIGGER);
		const rows = compareAnalyses(a, b);

		const bySameLabel = (label: string) => rows.find((r) => r.label === label);

		const filament = bySameLabel("Filament");
		expect(filament).toBeDefined();
		expect(filament!.same).toBe(false);
		expect(filament!.a).toBe("1.00 m");
		expect(filament!.b).toBe("2.00 m");

		const layers = bySameLabel("Layers");
		expect(layers).toBeDefined();
		expect(layers!.same).toBe(false);
		expect(layers!.a).toBe("1");
		expect(layers!.b).toBe("2");

		const slicer = bySameLabel("Slicer");
		expect(slicer).toBeDefined();
		expect(slicer!.same).toBe(true);
	});

	it("shows a dash rather than inventing a value for a fact neither file states", () => {
		const a = analyseText("G28\nG90\nM83\nG1 X1 Y1 E1 F1800");
		const rows = compareAnalyses(a, a);
		const hotEnd = rows.find((r) => r.label === "Hot end")!;
		expect(hotEnd.a).toBe("—");
		expect(hotEnd.same).toBe(true);
	});

	it("labels the machine-estimate row with its source, since a bare number is not comparable across two different sources", () => {
		const withM73 = analyseText([
			"G28", "G90", "M83", "M73 P0 R10", "G1 X1 Y1 E1 F1800",
		].join("\n"));
		const rows = compareAnalyses(withM73, withM73);
		const time = rows.find((r) => r.label === "Print time (this machine)")!;
		expect(time.a).toContain("M73");
	});
});
