import { AnalysisRunner, type AnalysisCollector } from "../model/analysisPass";
import { emptyMetadata, type SlicerMetadata } from "../model/gcode/metadata";
import type { FileGateway } from "../model/io/transfer";
import { runToString } from "../model/pipeline";
import { getStepDefinition } from "../model/steps/registry";
import { withDefaults, type Transform } from "../model/steps/types";

/** Build one step from its registry defaults plus overrides, the way the UI does. */
export function makeStep(type: string, overrides: Record<string, unknown> = {}): Transform {
	const def = getStepDefinition(type);
	if (def === null) throw new Error(`No such step: ${type}`);
	const config = { ...withDefaults(def, {}), ...overrides };
	return def.create(config as never, { scriptsTrusted: true });
}

/** Run one step over a block of text and return the output. */
export function runStep(
	type: string,
	overrides: Record<string, unknown>,
	input: string,
	meta: SlicerMetadata = emptyMetadata(),
): string {
	return runToString({ transforms: [makeStep(type, overrides)], meta }, input).output;
}

/** Run several steps in order. */
export function runSteps(
	steps: Array<Transform>,
	input: string,
	meta: SlicerMetadata = emptyMetadata(),
): ReturnType<typeof runToString> {
	return runToString({ transforms: steps, meta }, input);
}

/**
 * Run every collector over a block of text and return their results, the way `processFile`'s
 * analysis pass would (see `analysisPass.ts`) — for testing a step's `analysis()` collector without
 * going through the chunked I/O layer.
 */
export function collectAnalysis(
	collectors: Array<AnalysisCollector>,
	input: string,
	meta: SlicerMetadata = emptyMetadata(),
): ReadonlyMap<string, unknown> {
	const runner = new AnalysisRunner({ collectors, meta, totalBytes: input.length });
	let offset = 0;
	const lines = input.split("\n");
	const hasTrailingNewline = lines.length > 0 && lines[lines.length - 1] === "";
	if (hasTrailingNewline) lines.pop();
	for (const rawLine of lines) {
		const line = rawLine.endsWith("\r") ? rawLine.slice(0, -1) : rawLine;
		runner.line(line, offset);
		offset += rawLine.length + 1;
	}
	return runner.result();
}

/**
 * Run the analysis pass then the transform pass over the same text, exactly as `processFile` does —
 * for testing a step end to end against its own `analysis()` collector.
 */
export function runStepsWithAnalysis(
	steps: Array<Transform>,
	collectors: Array<AnalysisCollector>,
	input: string,
	meta: SlicerMetadata = emptyMetadata(),
): ReturnType<typeof runToString> {
	const analysisResults = collectAnalysis(collectors, input, meta);
	return runToString({ transforms: steps, meta, analysisResults }, input);
}

/** A small, realistic PrusaSlicer-shaped file used across the step tests. */
export const SAMPLE = [
	"; generated by PrusaSlicer 2.7.4+win64 on 2026-08-01 at 12:00:00 UTC",
	"; total layers count = 3",
	"M73 P0 R10",
	"M104 S210",
	"M140 S60",
	"G28 ; home all",
	"G21",
	"G90",
	"M83",
	"T0",
	";LAYER_CHANGE",
	";Z:0.2",
	"G1 Z0.2 F9000",
	"G1 X10 Y10 E1 F1200",
	"G1 X20 Y10 E2 F1800",
	";LAYER_CHANGE",
	";Z:0.4",
	"G1 Z0.4 F9000",
	"G1 X10 Y20 E3 F1800",
	";LAYER_CHANGE",
	";Z:0.6",
	"G1 Z0.6 F9000",
	"G1 X20 Y20 E4 F1800",
	"M104 S0",
	"M140 S0",
	"; filament used [mm] = 1234.5",
].join("\n");

/**
 * In-memory SD card, implementing the full FileGateway interface. Records the order of operations
 * so a write sequence can be asserted, and can be told to fail a specific upload or to corrupt the
 * reported size of the target, for the safety-path tests.
 */
export class FakeGateway implements FileGateway {
	files = new Map<string, string>();
	log: Array<string> = [];
	failUploadOn: string | null = null;
	corruptTargetSize = false;
	sentCodes: Array<string> = [];
	/** Reply to return from `sendCode`, or a function of the code for tests that need different
	 *  replies to different commands. */
	codeReply: string | ((code: string) => string) = "";

	constructor(initial: Record<string, string> = {}) {
		for (const [path, content] of Object.entries(initial)) this.files.set(path, content);
	}

	async download(path: string): Promise<Blob> {
		this.log.push(`download ${path}`);
		const content = this.files.get(path);
		if (content === undefined) throw new Error(`No such file: ${path}`);
		return new Blob([content], { type: "text/plain" });
	}

	async upload(path: string, content: Blob): Promise<void> {
		this.log.push(`upload ${path}`);
		if (this.failUploadOn === path) throw new Error("network died");
		this.files.set(path, await content.text());
	}

	async move(from: string, to: string): Promise<void> {
		this.log.push(`move ${from} -> ${to}`);
		const content = this.files.get(from);
		if (content === undefined) throw new Error(`No such file: ${from}`);
		this.files.delete(from);
		this.files.set(to, content);
	}

	async remove(path: string): Promise<void> {
		this.log.push(`remove ${path}`);
		this.files.delete(path);
	}

	async makeDirectory(path: string): Promise<void> {
		this.log.push(`mkdir ${path}`);
	}

	async sizeOf(path: string): Promise<number | null> {
		const content = this.files.get(path);
		if (content === undefined) return null;
		return this.corruptTargetSize ? 1 : new Blob([content]).size;
	}

	async sendCode(code: string): Promise<string> {
		this.log.push(`sendCode ${code}`);
		this.sentCodes.push(code);
		return typeof this.codeReply === "function" ? this.codeReply(code) : this.codeReply;
	}
}
