import { describe, expect, it } from "vitest";

import { parseDuration, parseMetadata } from "../model/gcode/metadata";

const PRUSA_HEAD = [
	"; generated by PrusaSlicer 2.7.4+win64 on 2026-08-01 at 12:00:00 UTC",
	"; total layers count = 214",
	"; estimated printing time (normal mode) = 2h 13m 5s",
	"M73 P0",
].join("\n");

const PRUSA_TAIL = [
	"; filament used [mm] = 4021.35",
	"; layer_height = 0.2",
	"; fill_density = 15%",
].join("\n");

describe("parseMetadata", () => {
	it("identifies PrusaSlicer and its version", () => {
		const meta = parseMetadata(PRUSA_HEAD, PRUSA_TAIL);
		expect(meta.slicer).toBe("PrusaSlicer");
		expect(meta.slicerVersion).toBe("2.7.4+win64");
	});

	it("reads the values the inspector shows", () => {
		const meta = parseMetadata(PRUSA_HEAD, PRUSA_TAIL);
		expect(meta.totalLayers).toBe(214);
		expect(meta.layerHeight).toBe(0.2);
		expect(meta.filamentMm).toBeCloseTo(4021.35);
		expect(meta.printTimeSeconds).toBe(2 * 3600 + 13 * 60 + 5);
	});

	it("identifies Cura and its colon-separated keys", () => {
		const meta = parseMetadata([
			";Generated with Cura_SteamEngine 5.6.0",
			";LAYER_COUNT:180",
			";Layer height: 0.15",
			";TIME:7200",
		].join("\n"));
		expect(meta.slicer).toBe("Cura");
		expect(meta.slicerVersion).toBe("5.6.0");
		expect(meta.totalLayers).toBe(180);
		expect(meta.layerHeight).toBe(0.15);
		expect(meta.printTimeSeconds).toBe(7200);
	});

	it("identifies OrcaSlicer ahead of PrusaSlicer", () => {
		// Orca files also mention PrusaSlicer in their config block, so ordering matters
		const meta = parseMetadata([
			"; generated by OrcaSlicer 2.1.0 on 2026-01-01",
			"; from PrusaSlicer settings",
		].join("\n"));
		expect(meta.slicer).toBe("OrcaSlicer");
	});

	it("identifies Simplify3D and its comma-separated keys", () => {
		const meta = parseMetadata([
			"; G-Code generated by Simplify3D(R) Version 5.1.2",
			";   layerHeight,0.2",
		].join("\n"));
		expect(meta.slicer).toBe("Simplify3D");
		expect(meta.layerHeight).toBe(0.2);
	});

	it("notices an embedded thumbnail", () => {
		const meta = parseMetadata("; thumbnail begin 16x16 512\n; AAAA\n; thumbnail end");
		expect(meta.hasThumbnail).toBe(true);
	});

	it("returns an empty result for a file with no metadata", () => {
		const meta = parseMetadata("G28\nG1 X10\n");
		expect(meta.slicer).toBe("unknown");
		expect(meta.totalLayers).toBeNull();
		expect(meta.values.size).toBe(0);
	});

	it("lets the head win over a repeated key in the tail", () => {
		const meta = parseMetadata("; layer_height = 0.2", "; layer_height = 0.3");
		expect(meta.layerHeight).toBe(0.2);
	});
});

describe("parseDuration", () => {
	it("parses hours, minutes and seconds", () => {
		expect(parseDuration("2h 13m 5s")).toBe(7985);
	});

	it("parses days", () => {
		expect(parseDuration("1d 2h")).toBe(93600);
	});

	it("returns null for text with no duration", () => {
		expect(parseDuration("unknown")).toBeNull();
	});
});
